prometheus:
  server_ip: 'YOUR_PROMETHEUS_SERVER_IP'
  port: 'YOUR_PROMETHEUS_SERVER_PORT'
  output_dir: './output'
  query_templates:
    - name: "EXAMPLE_NAME"
      expression: "YOUR_QUERY"
      labels:
        - key: "pod"
          value_from: "pod_name"
          match: "=~"
        - key: "namespace"
          value_from: "namespace"
          match: "="
      filename_suffix: "FILE_NAME"
  target:
    - type: "pod"
      pod_name: "TARGET_POD_NAME"
      namespace: "TARGET_NAMESPACE"