prometheus:
  server_ip: '192.168.9.10'
  port: '31003'
  output_dir: './output'
  query_templates:
    - name: "cpu_regex"
      expression: 'sum by(pod)(rate(container_cpu_usage_seconds_total{%s}[5m]))'
      labels:
        - key: "pod"
          value_from: "pod_name"
          match: "=~"
        - key: "namespace"
          value_from: "namespace"
          match: "="
      filename_suffix: "cpu"
  target:
    - type: "pod"
      pod_name: "test-.*-0"
      namespace: "kubeflow-user-example-com"